---
- !ruby/object:Rubber::Configuration::InstanceItem
  name: cms1
  domain: foo.com
  roles:
  - !ruby/object:Rubber::Configuration::RoleItem
    name: web
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: haproxy
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: app
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: passenger
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: apache
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: web_tools
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: graphite_server
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: graphite_web
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: db
    options:
      primary: true
  - !ruby/object:Rubber::Configuration::RoleItem
    name: mysql
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: mysql_master
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: collectd
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: monit
    options: {}
  instance_id: i-ffed6b32
  image_type: t2.micro
  image_id: ami-ca381398
  security_groups:
  - default
  - web
  - web_tools
  external_host: ec2-54-179-142-42.ap-southeast-1.compute.amazonaws.com
  external_ip: 54.179.142.42
  internal_host: ip-172-31-1-181.ap-southeast-1.compute.internal
  internal_ip: 172.31.1.181
  zone: ap-southeast-1a
  provider: aws
  platform: linux
  root_device_type: ebs
  static_ip: 54.179.142.42
- volumes: {}
  static_ips:
    cms1: 54.179.142.42
