graylog_server_version: "0.90.0"
graylog_server_prefix: "/usr/local"
graylog_server_dir: "#{graylog_server_prefix}/graylog2-server-#{graylog_server_version}"
graylog_server_pid_file: "/var/run/graylog-server.pid"
graylog_server_port: 12201
graylog_server_syslog_port: 12514

graylog_web_version: "0.90.0"
graylog_web_prefix: "/usr/local"
graylog_web_dir: "#{graylog_web_prefix}/graylog2-web-interface-#{graylog_web_version}"
graylog_web_pid_file: "/var/run/graylog-web.pid"
graylog_web_port: 9000

graylog_web_username: admin
graylog_web_password: admin1

graylog_mongo_database: graylog2
graylog_elasticsearch_index: "graylog2_#{Rubber.env}"

web_tools_proxies:
  graylog:
    role: graylog_web
    port: "#{graylog_web_port}"
    path: /
  graylog_server_api_browser:
    role: graylog_server
    port: 12900
    path: /api-browser/

role_dependencies:
  graylog_server: [graylog_mongodb, graylog_elasticsearch]
  graylog_mongodb: [mongodb]
  graylog_elasticsearch: [elasticsearch]

roles:
  graylog_server:
    packages: [openjdk-7-jdk, mongodb-10gen]
  graylog_web:
    packages: [openjdk-7-jdk]

# This was auto-generated by Rubber and is unique to your machine.  Feel free to regenerate if you'd like.
# You may want to move this to your rubber-secret.yml to keep it out of version control.
graylog_server_secret: d59d7dfd2ebeb2d7f87664e59329446070933421b9c9432d2f4f20b9794742c5540b77ec3330135daca421b5af0ab52861233c4e5aee4e954f26244ac46c54335181291c51848710de7aee7140be06914050ffe520297c158d2b6ad9e4494ecc

# This was auto-generated by Rubber and is unique to your machine.  Feel free to regenerate if you'd like.
# You may want to move this to your rubber-secret.yml to keep it out of version control.
graylog_web_secret: daa970f1ebb2af9360ada960c957a80d7f1a4714acef5b6a7ea97e3bca0e89e552e3fa23b4c887167060e4c214d9ea5f75587b2fc57ae39f00441b800a17c87da8807014cbd9af599b29b7a0bdb0572ff8db2f3a0f05a2ad7d7e4b23f9f8d27a
